version: '3'
tasks:
  init:
    cmds:
    - go mod tidy
    - go install github.com/a-h/templ/cmd/templ@latest
    - go install github.com/cosmtrek/air@latest
    # need rust/cargo for this, find alternatives?
    - cargo install sleek
    # - brew install tailwindcss
    # - pnpm i
  run:
    cmds:
    - air
  tidy:
    cmds:
    - go mod tidy
  hot-reload:
    cmds:
    - tailwindcss -i view/css/app.css -o public/styles.css 
    - templ generate --watch --cmd="go run main.go" --proxy="http://localhost:3000"
