- name: Badger Divide (Reverse)
  slug: badger-divide
  location: Scotland - Glasgow to Inverness
  date: 2026-04-01
  gpx: /public/routes/Badger_divide_reverse.gpx
  packlist: https://lighterpack.com/r/tjgsqt
